reana:
  secrets:
    login:
      escape-iam:
        # TODO: set this
        consumer_key: "testkey"
        consumer_secret: "testsecret"
        
nfs-server-provisioner:
  enabled: true
  persistence:
    enabled: true
    storageClass: standard