repos:
  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
    - id: codespell
      additional_dependencies:
        - tomli

  - repo: https://github.com/norwoodj/helm-docs
    rev: "v1.14.2"
    hooks:
    - id: helm-docs-built
      args:
        - "--chart-search-root=./vre"

  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.24
    hooks:
    - id: helmlint
      args:
        - "--chart-dir=vre"

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.29.4
    hooks:
    - id: check-jsonschema
      name: Validate Helm templates with kubeconform
      files: ^vre/templates/.*\.yaml$
      types: [yaml]
      entry: bash -c '
        helm template vre ./vre | kubeconform -strict -ignore-missing-schemas -summary -output pretty - '

      language: system
      pass_filenames: false
