apiVersion: skaffold/v4beta12
kind: Config
metadata:
  name: cern-vre
deploy:
  helm:
    hooks:
      before:
        - host:
            command:
            - sh
            - -c
            - |
              if kubectl cluster-info; then
                echo "found k8s cluster, will install in it";
              else
                echo "found NO k8s cluster, will create one with kind. If that's not what you want, please interrupt this command make sure a k8s cluster is accessible before running skaffold";
                kind create cluster
                sleep 1
              fi
    releases:
      - name: cern-vre
        chartPath: vre
        valuesFiles:
         - vre/values.yaml
       # copy vre/values-custom-copy.yaml to vre/values-custom.yaml, set the necessary values, and uncomment this line
         - vre/values-custom.yaml
        version: 0.1.0-dev0
