apiVersion: skaffold/v4beta12
kind: Config
metadata:
  name: escape-vre
deploy:
  helm:
    releases:
      - name: escape-vre
        chartPath: vre
        valuesFiles:
         - vre/values.yaml
       # copy vre/values-custom-example.yaml to vre/values-custom.yaml, set the necessary values, and uncomment this line
         - vre/values-custom.yaml
        version: 0.1.0-dev0
